### ISSUE TITLE
Atualização dados Brasil e estados

### ISSUE THREAD

**Issue by thaispaiva** [covid19br/covid19br.github.io#104]
Houve algum problema na divulgação dos dados do MS? Os dados por estados e do Brasil não estão sendo atualizados desde o dia 16/11.

**Comment by gburin** [comment]
Olá Thais,

desculpe pela falha. Atualizei os arquivos localmente mas acabei esquecendo de atualizar o repositório. Está feito para os últimos 3 dias.

**Comment by thaispaiva** [comment]
Ah ótimo, obrigada!
