### ISSUE TITLE
Atualização dos dados do Brasil e estados

### ISSUE THREAD

**Issue by thaispaiva** [covid19br/covid19br.github.io#107]
Olá! Houve alguma pausa nas atualizações dos dados de estados e o total do Brasil?

**Comment by gburin** [comment]
Olá Thais, tudo bem?

Desculpe a demora em responder. Eu que atualizava os dados diariamente, mas
mudei de país no fim do ano, e ainda não tenho um computador que me permita
continuar as atualizações.

Tão logo eu arrume um, volto a atualizar.

Peço desculpas pelo transtorno.

Até mais

**Comment by rafalopespx** [comment]
Paramos de coletar esses dados
