### ISSUE TITLE
Creative commons é a melhor opção de licença?

### ISSUE THREAD

**Issue by rafamanzo** [covid19br/covid19br.github.io#109]
Parabéns pelo trabalho! Acompanho frequentemente as atualizações e só tenho elogios.

Não sou advogado, mas um ponto que gostaria de levantar é o do título da issue, pois a própria creative commons não recomenda o uso para software: https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software.

Procurei no commit (01447e17ca68c844ad792046042d140d3df5a411) e na issue original (https://github.com/covid19br/covid19br.github.io/issues/29) e não encontrei alguma discussão sobre isso, mas imagino que a tenham tido na época da definição. Desculpe se for um questionamento repetido :)

Parabéns a todos pelo trabalho mais uma vez!

**Comment by renatocoutinho** [comment]
A escolha da Creative Commons é porque este repositório é basicamente o conteúdo do site, não exatamente software (inclusive o software que gera as análises todas ficam em outro repositório) - e para conteúdo Creative Commons é uma licença adequada.
