### ISSUE TITLE
caixas da página de info referenciadas

### ISSUE THREAD

**Issue by renatocoutinho** [covid19br/covid19br.github.io#16]
Cada gráfico/texto usa a info de uma das caixas só, seria legal ter anchors e colocar os links direto pra anchor correta dentro da página, pra ser mais específico - como esta agora o leitor demora pra achar de qual info ele precisa.

**Comment by badain** [comment]
seria interessante incluir um Table of Contents na página info, usando as anchors

**Comment by badain** [comment]
Agora a página de informações conta com um índice para facilitar a navegação e tornar a busca por conteúdos mais rápida. Todos os títulos de conteúdos estão ancorados, então também é possível redirecionar o usuário para blocos específicos utilizando `informações.html#nome-do-titulo`

**Comment by renatocoutinho** [comment]
Posso reabrir pra pedir que as referências sejam incluídas onde necessário? Praticamente todas as páginas têm links praí (brasil, estados, município SP, leitos...). Talvez @vsudbrack possa ver isso.

**Comment by vsudbrack** [comment]
Feito! Espero ter achado todos os "clique aqui"... se acharem outro me avisem!

**Comment by renatocoutinho** [comment]
Beleza, valeu! (na próxima pode apertar o "Close"!)

**Comment by renatocoutinho** [comment]
Reabrindo: página com cálculo de Re, e de TD, não tem link pra página de info (pra segunda não sei se tem explicado lá? Se não, precisava ter)

**Comment by vsudbrack** [comment]
Adicionado tanto no TD quanto Re.
