### ISSUE TITLE
Mais 3 matérias: Globo, G1 e Canal Questão de Ciência

### ISSUE THREAD

**Issue by piklprado** [covid19br/covid19br.github.io#27]
https://oglobo.globo.com/sociedade/para-especialistas-brasil-vive-apagao-de-dados-sobre-covid-19-1-24406659

https://g1.globo.com/bemestar/coronavirus/noticia/2020/04/30/mortes-por-sindromes-respiratorias-em-2020-superam-media-dos-ultimos-10-anos-apontam-dados-da-fiocruz.ghtml

Fatos e Dúvidas: a ciência e o coronavírus #02: https://www.youtube.com/watch?v=s3ndi1F-Bmg

**Comment by badain** [comment]
adicionadas
