### ISSUE TITLE
Dados para dia 04/05 diferentes na plataforma do MS

### ISSUE THREAD

**Issue by deborafmag** [covid19br/covid19br.github.io#30]
Boa tarde, pessoal.
Parece haver uma diferença entre os dados do repositório referente ao Brasil e seus estados no dia 04/05 se comparado ao dados da plataforma do Ministério da Saúde em https://covid.saude.gov.br/.
Entre alguns exemplos, temos:
No repositório: dia 04/05 o Brasil apresenta 4,075 novos casos.
                          dia 04/05 o Ceará apresenta um total de 8,501 casos.
Na plataforma do MS: dia 04/05 o Brasil apresenta 6,633 novos casos.
                                     dia 04/05 o Ceará apresenta um total de 11,040 casos.
Att.
Débora

**Comment by gburin** [comment]
Olá Débora,
essa diferença foi por causa de uma segunda atualização nos dados do MS ontem, após o horário que eu baixei os dados de lá. Acabei de atualizar novamente ([aqui] https://github.com/covid19br/covid19br.github.io/commit/96c852e71fe9eb8c62f04d3709f0a74d67613120)
Obrigado pelo aviso!

**Comment by deborafmag** [comment]
Oi Gustavo,
Imaginei que isso tivesse acontecido. Obrigada pela eficiente resposta!
Att.
Débora

**Comment by renatocoutinho** [comment]
opa, a atualização dos mesmos dados é ignorada pelo robô, então rodei a atualização na mão aqui, acho que agora tá fechado de verdade
