### ISSUE TITLE
Implementar troca de escalas no site

### ISSUE THREAD

**Issue by diogro** [covid19br/covid19br.github.io#35]
O gráfico de casos hospitalizados em SP tá em escala log, mas o crescimento é quase linear há  um mês, será que precisa ficar em log? Como não tá crescendo tão rápido acho que não precisa.

**Comment by badain** [comment]
podemos implementar uma opção de trocar a escala de exibição no site, o que acha?

**Comment by diogro** [comment]
Por mim perfeito! É só gerar as duas versões no ggplot

**Comment by piklprado** [comment]
Concordo!

**Comment by renatocoutinho** [comment]
Gráfico semanal já está em escala linear, acumulado deve ficar em log mesmo, se não fica difícil de ver.
