### ISSUE TITLE
Pagina da projeção de leitos pra SP

### ISSUE THREAD

**Issue by diogro** [covid19br/covid19br.github.io#36]
Tem gráficos prontos no pasta outputs/municipio_SP/projecao_leitos/figuras. Esse é um bom lugar pra elas? 
Podemos criar um card novo na pagina de SP com essas figura, e um menu SRAG/Covid-19 ?

**Comment by badain** [comment]
Atualmente os gráficos estão sendo armazenados no pasta /web
