### ISSUE TITLE
Otimizar a obtenção dos horários de atualização

### ISSUE THREAD

**Issue by renatocoutinho** [covid19br/covid19br.github.io#47]
Os arquivos de data de last update têm dado muito problema com os robôs, eles frequentemente levam a conflitos triviais entre commits que afetam plots / sub-páginas diferentes. Não seria melhor não deixar nenhuma atualização automática disso, e deixar um "processo" independente só pra isso? Opções que pensei são:
1. um js que recupera os dados a partir da página do github; ou
2. um outro robô que pega a data do último commit de todos os cmponentes da página

O 1 não sei se é vável, o 2 é fácil. O ponto importante é que nenhum script atualize essas datas, fique tudo por conta desse outro script pra nunca ter conflito no merge.

**Comment by badain** [comment]
`document.lastModified` retorna a última atualização do arquivo html via javascript nativo

**Comment by AndreaSanchezTapia** [comment]
Vamos modificar o que for posível em nowcasting - tabelas.web() https://github.com/covid19br/nowcasting/issues/19

**Comment by renatocoutinho** [comment]
@badain agora tem arquivos data_atualizacao_*.csv com essa data pra cada plot (srag/covid casos/obitos), só precisa pegar daí a data da última atualização (na verdade não tem como separar srag e covid, é a mesma página, tudo bem)

**Comment by renatocoutinho** [comment]
O problema principal já foi corrigido, mas agora tem outro: ele mostra a data de atualização antes da atualização de fato acontecer (porque o site demora mais pra atualizar do que o github).

**Comment by renatocoutinho** [comment]
Alguma razão pra apontar pro arquivo txt no github e não no endereço do próprio site?! Assim eles atualizam juntos, faz mais sentido...
