### ISSUE TITLE
Trocar cor pontos no site

### ISSUE THREAD

**Issue by piklprado** [covid19br/covid19br.github.io#5]
Sugestão usuários: trocar a cor dos pontos projetados em azul para vermelho ou outra cor que se destaque melhor.

**Comment by renatocoutinho** [comment]
Closed by PR #3

**Comment by piklprado** [comment]
> Ola pessoal, uma pessoa mandou uma sugestão por e-mail de trocar a cor dos pontos projetados em azul para vermelho ou outra cor que se destaque melhor. Segundo ele as cores azul e preto confundem quem está vendo o gráfico. <@U010FSKNLCC>
<sub>[View in Slack](https://obscovid19br.slack.com/archives/C0106AUA47K/p1584805289004100)</sub>

**Comment by piklprado** [comment]
> Oi pessoal, sugiro a utilização do <https://colorbrewer2.org/#type=sequential&amp;scheme=BuGn&amp;n=3> para gerar paleta de cores, dá pra mudar o tipo de visualização desejada e também fazer algo seguro para daltônicos, é padrão em algumas revistas de ponta em computação gráfica
<sub>[View in Slack](https://obscovid19br.slack.com/archives/C0106AUA47K/p1584806052007800)</sub>
