### ISSUE TITLE
Qual o critério para definir semanas na seção reportagem?

### ISSUE THREAD

**Issue by piklprado** [covid19br/covid19br.github.io#51]
Na seção de reportagem a semana 1 tem matérias de 2 a 12 de maio. O que deve estar errado, mas me levou à pergunta se a definição de semana 1, 2, etc desta seção está combinado. porque pode tanto ser até um dai específico da semana (p.ex. domingo), ou contar 7 dias a partir do dia 01 de cada mês.

**Comment by renatocoutinho** [comment]
não devia ser por semana epidemiológica? :p Falando sério, nunca entendi pq fazer semanal, o volume não é tão grande que fazer mensal seja um problema (especialmente se você respeita a ordem cronológica)

**Comment by badain** [comment]
Eu mantive semanal porque nos celulares, com espaço pequeno da tela, a lista que parece okay no desktop fica gigante. Eu honestamente defini o que era semana olhando pro meu calendário do computador e contando a semana do mês (que começa no domingo). Acho que quem foi adicionando as últimas matérias só esqueceu de adicionar uma nova semana.

**Comment by piklprado** [comment]
Por mim tudo certo qualquer critério. Que tenha semanas de 7 dias, claro :)

**Comment by IriLrnr** [comment]
Eu arrumei! Considerei a primeira semana do dia 1 ao 7, e a segunda do 8 ao 14.
