### ISSUE TITLE
Análise da nova página do município de SP

### ISSUE THREAD

**Issue by kraenkel** [covid19br/covid19br.github.io#55]
- [x] Observação geral: eu creio que devemos evitar ilustrações que sejam meio engraçadas/irônicas/fofas. Acho que o site deve ter um tom sóbrio. 

## Aba. “Casos graves”

- [ ] Gráficos de casos Covid-19 acumulado e casos Srag acumulados:  os gráficos que se veem depois de clicar tem valores nos eixos muito mais claros. Poderia-se ter isso nos gráficos que são visualizados?  Ou então ter uma legende “clique non gráfico para ver em detalhes”.

- [x] Sobre o texto: não há explicação do que seja SRAG.

- [x] Os gráficos  sobre taxas de duplicação ficam muito embaixo na página e podem passar despercebidos. 

- [x] O botão “por observar casos de SRAG”está repetido.

- [ ] Também passa despercebida a possibilidade de ver casos acumulados e casos diários.

## Aba “taxa de infecção”

- [x] Os gráficos não sãos os corretos, quando na navegação anterior estava-se em “diários”ou invés de acumulados.     Há um bug que faz com que não sejam exibidos os gráficos certos em diversas instâncias nesta aba.

**Comment by badain** [comment]
Adicionei as demandas que faltam na Issue #49
