### ISSUE TITLE
Remover as assinaturas Guimarães lab

### ISSUE THREAD

**Issue by diogro** [covid19br/covid19br.github.io#57]
O Miúdo tinha pedido para remover as assinaturas de Guimarães Lab nos painéis da pagina principal. Eu tinha tirado mas alguém colocou de volta. Pode retirar.

**Comment by vsudbrack** [comment]
Corrigido (PS: essas coisas tem que deixar avisado no #site ou aqui porque senão a gente não sabe e coloca de novo. Mas agora já repassei o recado.)
