### ISSUE TITLE
Casos SRAG são sempre graves

### ISSUE THREAD

**Issue by piklprado** [covid19br/covid19br.github.io#63]
Sugestão do José Olímpio (SMS) para os títulos de gráficos e seções que estejam: "Casos "Graves de SRAG": 

"Casos graves de SRAG" é pleonasmo, poderia ser só "Casos de SRAG" ou "Casos de Síndrome Respiratória Aguda Grave"

**Comment by diogro** [comment]
To procurando isso no código e não acho. Como é feito o título desses gráficos?

**Comment by diogro** [comment]
Never mind... feito!
