### ISSUE TITLE
Municipios SP casos graves e obitos: graficos com cores invertidas no diarios/acumulados

### ISSUE THREAD

**Issue by mcrillo** [covid19br/covid19br.github.io#64]
Na aba Acumulados, notificados/observados estao em azul e estimado em vermelho.
Na aba Diarios, notificados em vermelho e estimados em azul. 
Como a legenda eh unificada, os graficos tem que estar com as cores consistentes.

**Comment by diogro** [comment]
Arrumei no código que gera os plots, mas não consegui rodar os plots, deu um erro no update_municipio.R

Alguem pode tentar? @renatocoutinho @badain

**Comment by renatocoutinho** [comment]
feito, mas ainda tá errado o diário proaim, pq usa uma versão antiga - acho que tava na hora de largar a proaim?

**Comment by renatocoutinho** [comment]
Troquei proaim pra sivep ontem, precisa atualizar o texto, mas esta issue pode fechar.
