### ISSUE TITLE
Erro de arredondamento? No momento o R_e está entre 1 e 1.

### ISSUE THREAD

**Issue by francocarol** [covid19br/covid19br.github.io#73]
Se o valor de R_e está sendo arredondado, poderíamos adicionar 1 ou 2 dígitos aós a vírgula, para a frase fazer sentido.

**Comment by vsudbrack** [comment]
Bem observado, Carol!
Acho que o problema é que o limite inferior é arredondado para cima, e o limite superior é arredondado para baixo.
Sugestão de correção: arredondar para baixo entre (.0 e .5), e arredondar para cima (.5 e 0.9).

Ademais, adicionar dígitos depois da vírgula em função da diferente (se a diferença é menor de 0.2 -> adicionar mais uma casa decimal). Este segundo me soa mais difícil de implementar

**Comment by IriLrnr** [comment]
Em que página está esse problema?

**Comment by renatocoutinho** [comment]
Tá na de municípios, mas acho que o erro está no output dos scripts em R, vou abrir uma issue no repo nowcasting (https://github.com/covid19br/nowcasting/issues)
