### ISSUE TITLE
Incluir a Carta de 8/5 na seção "Análises"

### ISSUE THREAD

**Issue by piklprado** [covid19br/covid19br.github.io#75]
A carta está só em formato PDF. Em um link que está ficando meio perdido já. Acho importante manter este link, pq está na reportagem do G1. Mas sugiro fazer uma versão em html da carta e incluir na seção de análises.

**Comment by renatocoutinho** [comment]
Acho que a proposta do Paulo era só copiar e colar o texto - nem tem gráfico, é só texto, então deve dar bem pouco trabalho.

**Comment by badain** [comment]
Podemos fazer uma versão HTML da carta e deixar um link para download do PDF no final. Também são interessantes botões de compartilhamento no site.

**Comment by vsudbrack** [comment]
A carta foi add em html com link para download no final, mantendo o link original.
