### ISSUE TITLE
Página de DRS's (em desenvolvimento, branch dev_nowcasting)

### ISSUE THREAD

**Issue by piklprado** [covid19br/covid19br.github.io#77]
* [x] Na aba de taxa de infecção aparecem os plots de n de casos
* [x] Na aba de Tempo de duplicação tb  aparecem os plots de n de casos
* [x] Quando mudo de uma DRS para outra parece que fica um mesmo plot de casos graves para SRAG e COVID. daí quando clico em casos acumulados e volto aos casos diários mostra os plots corretos.
* [x] Seção leitos ocupados não está funcionando
* [ ] robô de leitos está estável?
* [ ] Incluir no texto das seções que o nowcasting é feito cortando-se os últimos 5 dias da base de dados, enão os últimos 2 dias.

**Comment by renatocoutinho** [comment]
Deixei aberto porque falta testar. 

O último tópico não é relacionado - @piklprado não sei bem o que você quis dizer, o texto não menciona exatamente um trim, só o número de dias da projeção... se quiser, isso dá pra mexer direto no DRS.html, só buscar pelo trecho e editar.
