### ISSUE TITLE
trocar "taxa de infecção" por "R efetivo" em todas análises

### ISSUE THREAD

**Issue by renatocoutinho** [covid19br/covid19br.github.io#79]
Acho que isso aparece em municipios e na página nova (branch dev_nowcasting) de DRSs, mas era bom checar se tem em outros lugares (card na página principal? infos técnicas?)

**Comment by vsudbrack** [comment]
Trocado no municipios.html, no index.html e nas informacoes.html no master, e no DRS.html do dev_nowcasting.
