### ISSUE TITLE
Dados Brasil com dia 30/05 a mais na última linha

### ISSUE THREAD

**Issue by thaispaiva** [covid19br/covid19br.github.io#80]
Os dados do dia 30/05 estão repetidos após o dia 31/05 no arquivo "BrasilCov19.csv".

**Comment by renatocoutinho** [comment]
acho que isso não afeta os resultados, mas era bom limpar @gburin

**Comment by renatocoutinho** [comment]
OK, o robô não funcionou por causa disso, apaguei dos dados processados (mas não dos brutos, naturalmente)

**Comment by gburin** [comment]
O problema está na tabela original. O dia 29/05 está faltante, e inseriram
uma linha bizarra para todas as cidades com a data de 30/05. Devem arrumar
na tabela de hoje, e como o Renato já arrumou na unha, vou esperar para ver
antes de alterar o script.

*Gustavo Burin*
Instituto de Biociências
Universidade de São Paulo
Tel: (11) 98525-8948

**Comment by thaispaiva** [comment]
No arquivo EstadosCov19.csv também está repetindo a data 30/05 para todos os estados (foi apagado apenas para o DF).

**Comment by thaispaiva** [comment]
Deletei as linhas repetidas aqui e enviei um pull request #81.

**Comment by renatocoutinho** [comment]
Obrigado, @thaispaiva !
