### ISSUE TITLE
Macapá - AP

### ISSUE THREAD

**Issue by MarceloB87** [covid19br/covid19br.github.io#87]
O título da página informa "Casos graves de COVID-19 e SRAG em São Paulo".
Ao clicar em qualquer outro link e submenu (Leitos ocupados, óbitos, etc) a página redireciona para os gráficos do município de São Paulo.

**Comment by renatocoutinho** [comment]
Opa, tem que esperar eu gerar, entrou por último na lista então não coloquei ainda, ainda não tem data de last.update.
