### ISSUE TITLE
Atualização dados por estados

### ISSUE THREAD

**Issue by thaispaiva** [covid19br/covid19br.github.io#88]
Os dados brutos e os arquivos 'BrasilCov19.csv' e 'EstadosCov19.csv' continuarão a ser atualizados, mesmo com a mudança da forma de divulgação do Ministério da Saúde?

**Comment by renatocoutinho** [comment]
Acho muito difícil. O brasil.io está fazendo uma compilação a partir de dados de secretarias municipais e estaduais, acho que no momento é a melhor fonte pra casos e óbitos totais. A gente tem trabalhado em cima da base SIVEP, mas nela só entram casos hospitalizados, não tem como chegar no número total (mas é melhor pra acompanhar taxas de crescimento etc.)

**Comment by thaispaiva** [comment]
Ok, obrigada!

**Comment by gburin** [comment]
@thaispaiva 

Desenvolveram uma extensão para o Chrome que apresenta o painel do MS como era antes, bem como gera um botão de download para os dados da mesma forma que era feito anteriormente. Os dados estão agora atualizados para ontem e hoje, e o link para a extensão é [esse aqui](https://chrome.google.com/webstore/detail/transpar%C3%AAncia-covid-19/cmfmagjdlcbepiagpikdhcmbdappdcof?authuser=0&hl=pt-BR).

Vou continuar monitorando a situação para ver se a extensão permanece funcionando.
