### ISSUE TITLE
padronizar plots na página municípios

### ISSUE THREAD

**Issue by saramortara** [covid19br/covid19br.github.io#89]
Na página municípios os plots aparecem ora em linha, ora em coluna. Na aba casos os plots aparecem organizados em uma mesma coluna (o que está bom) mas nas outras abas (óbitos, R efetivo, leitos ocupados, tempo de duplicação) os gráficos estão em uma mesma linha. Quando em linha estão pequenos e com uma área branca embaixo do gráfico. Seria melhor padronizar todas as abas em colunas

**Comment by mcrillo** [comment]
Ja fiz pro obitos e Re, vejam se ficou bom no desktop e mobile por favor.
Falta resolver: 
[ ] leitos ocupados (é so um grafico e fica com espaco branco em cima e embaixo no desktop)
[ ] TD (se tiver tempo faco hoje a noite)

**Comment by mcrillo** [comment]
Alguem ja fez o TD

**Comment by mcrillo** [comment]
Os graficos do R efetivo ficam cortados nas extremidades no meu celular. Nao sei resolver.

**Comment by renatocoutinho** [comment]
Parece não ter mais problemas? @mcrillo
