### ISSUE TITLE
Link errado para relatórios leitos nas DRSs

### ISSUE THREAD

**Issue by piklprado** [covid19br/covid19br.github.io#94]
Na aba "Leitos Ocupados" para as DRSs do Estado de SP os links no texto:

'Para saber mais detalhes, consulte o relatório completo `aqui`. Todos os relatórios anteriores podem ser encontrados `aqui`."

Leva aos relatórios do município de São Paulo.

**Comment by renatocoutinho** [comment]
Não tem relatório por DRS, mas também não tem mais link, só aparece pra município SP.
