### ISSUE TITLE
Planilha de Estados e Brasil consolidada

### ISSUE THREAD

**Issue by marcosop** [covid19br/covid19br.github.io#95]
Caros, eu venho utilizando o repositório de vocês a bastente tempo para análises sobre o Covid. Para tal, utilizo as planilhas (csv) de Estados e Brasil consolidadas. Porém, essas planilhas não são atualizadas há 2 dias. Vocês vão continuar a gerar essas planilhas? Att.

**Comment by gburin** [comment]
Olá @marcosop, tudo certo?

Ontem o MS não disponibilizou a planilha para download (o link apontava para a planilha do dia 18). Acabei de atualizar os csvs com os dados de ontem e hoje.

https://github.com/covid19br/covid19br.github.io/commit/8763cbdc54300506beed837757dee56c23dce119

De maneira geral, só não atualizaremos quando o MS não disponibilizar as atualizações. Nas últimas semanas isso aconteceu alguns dias, porém foi normalizado no dia seguinte.

Abraços
