### ISSUE TITLE
Atualização dados do Estados e Brasil

### ISSUE THREAD

**Issue by marcosop** [covid19br/covid19br.github.io#96]
Caros, sempre utilizo o repositório de você para análise. Mas os dados consolidados dos Estados e do Brasil não foi atualizado com os dados do Ministŕio liberados no dia 01/07. Algum problema?

**Comment by gburin** [comment]
O MS demorou para liberar a planilha com os dados ontem, o que acontece às vezes. Está atualizado agora. https://github.com/covid19br/covid19br.github.io/commit/7f3bee4af7b2bb85dc64326869cc21347f44f224
