### ISSUE TITLE
Texto incorreto na aba Estados nova

### ISSUE THREAD

**Issue by Leo-Souto** [covid19br/covid19br.github.io#98]
Texto para o R efetivo está escrito para municípios.
"Estimamos o da epidemia de COVID-19 no Brasil diariamente no município de <estado>"

![image](https://user-images.githubusercontent.com/16999127/86519909-e099fc00-be15-11ea-809e-9b315ee4cc0a.png)

**Comment by renatocoutinho** [comment]
Corrigido no  0f1beb9
